

module.exports = {
    '4000': 'The statement contains an invalid syntax or unsupported SQL statement',
    '4001': 'The statement contains an invalid analyzer definition.',
    '4002': 'The name of the table is invalid.',
    '4003': 'Field type validation failed',
    '4004': 'Possible feature not supported (yet)',
    '4005': 'Alter table using a table alias is not supported.',
    '4006': 'The used column alias is ambiguous.',
    '4031': 'Only read operations are allowed on this node.',
    '4041': 'Unknown table.',
    '4042': 'Unknown analyzer.',
    '4043': 'Unknown column.',
    '4044': 'Unknown type.',
    '4045': 'Unknown schema.',
    '4046': 'Unknown Partition.',
    '4047': 'Unknown Repository.',
    '4048': 'Unknown Snapshot.',
    '4091': 'A document with the same primary key exists already.',
    '4092': 'A VersionConflict. Might be thrown if an attempt was made to update the same document concurrently.',
    '4093': 'A table with the same name exists already.',
    '4094': 'The used table alias contains tables with different schema.',
    '4095': 'A repository with the same name exists already.',
    '4096': 'A snapshot with the same name already exists in the repository.',
    '4097': 'A partition for the same values already exists in this table.',
    '5000': 'Unhandled server error.',
    '5001': 'The execution of one or more tasks failed.',
    '5002': 'one or more shards are not available.',
    '5003': 'the query failed on one or more shards',
    '5004': 'creating a snapshot failed',
    '5030': 'the query was killed by a kill statement'
};
